[package]
name = "gqls-syntax"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = "0.20"
tree-sitter-traversal = "0.1"

[dependencies.vfs]
path = "../vfs"

[dev-dependencies]
expect-test = "1"

[build-dependencies]
cc = "1"
